from __future__ import annotations

from pathlib import Path
import yaml

from .eligibility import evaluate_eligibility
from .matching import technical_fit
from .profile import ROOT, load_profile


def _priority(eligibility: str, fit_level: str) -> str:
    if eligibility == "FAIL":
        return "C"
    if fit_level in {"very_high", "high"}:
        return "A"
    if fit_level == "medium":
        return "B"
    return "C"


def evaluate_pending(*, dry_run: bool = False, job_id: str | None = None) -> dict[str, object]:
    profile = load_profile()
    roots = [ROOT / "jobs" / job_id] if job_id else sorted((ROOT / "jobs").glob("*"))
    evaluated = 0
    results: list[dict[str, object]] = []
    for job_dir in roots:
        jd_file = job_dir / "job.md"
        if not job_dir.is_dir() or not jd_file.exists():
            continue
        jd = jd_file.read_text(encoding="utf-8")
        meta_file = job_dir / "metadata.yml"
        metadata = yaml.safe_load(meta_file.read_text(encoding="utf-8")) if meta_file.exists() else {}
        metadata = metadata if isinstance(metadata, dict) else {}
        title = str(metadata.get("title") or job_dir.name)
        eligibility = evaluate_eligibility(jd, profile)
        fit = technical_fit(title, jd)
        priority = _priority(eligibility.overall, str(fit.get("level", "low")))
        row = {"job_id": job_dir.name, "title": title, "priority": priority, "eligibility": eligibility.to_dict(), "fit": fit}
        results.append(row)
        evaluated += 1
        if not dry_run:
            (job_dir / "evaluation.md").write_text(
                "# Job Evaluation\n\n"
                f"Priority: **{priority}**\n\n"
                "This evaluation was generated by auto-job from the canonical profile and eligibility/matching modules.\n\n"
                "```yaml\n" + yaml.safe_dump(row, sort_keys=False) + "```\n",
                encoding="utf-8",
            )
    return {"status": "success", "evaluated": evaluated, "results": results, "dry_run": dry_run}
